language: node_js

node_js: 10

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
jobs:
  include:
    - stage: lighthouse
      if: type = pull_request
      install: yarn add --dev ebidel/lighthouse-ci wait-for-netlify-preview
      script: lighthouse-ci "$(wait-for-netlify-preview)"
